# _.env.txt - ENHANCED VERSION
NODE_ENV=production
PORT=3000
SESSION_SECRET=1Sampai100
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

# Enhanced Retry Configuration
MAX_RETRIES=3
RETRY_BASE_DELAY=10000
RETRY_MAX_DELAY=60000
RETRY_FACTOR=2

# Auto-loop Configuration
AUTO_LOOP=true
LOOP_INTERVAL=1800000
MAX_SESSIONS=5
DEFAULT_TARGET_URL=https://cryptoajah.blogspot.com

# Enhanced Timeout Settings
BROWSER_TIMEOUT=120000
NAVIGATION_TIMEOUT=150000
PROXY_TEST_TIMEOUT=30000

# Health Check Configuration
HEALTH_CHECK_INTERVAL=60000
MAX_SESSION_DURATION=600000

# Security & Proxy Enforcement
ENABLE_HELMET=true
ENABLE_CORS=true
FORCE_PROXY=true
NO_DIRECT_CONNECTION=true

# Web Proxy Settings
WEB_PROXY_TIMEOUT=45000
WEB_PROXY_RETRY_COUNT=3
ENABLE_WEB_PROXY_FORM_FILL=true
ENHANCED_INPUT_DETECTION=true
AUTO_ENTER_FALLBACK=true

# Performance Optimization
ENABLE_MINIMAL_LOGGING=true
MAX_CONCURRENT_SESSIONS=5